// Static Icons
export {
  AjilSymbol,
  IconLoanProducts,
  IconApplyFinancing,
  IconLoanCalculator,
  IconBusinessFinancing,
  IconPersonalFinancing,
  IconMurabaha,
  IconTrackApplication,
  IconCustomerSupport,
  IconHome,
  IconSettings,
  IconPayments,
  IconSecurity,
  IconCarFinancing,
  IconQuickApproval,
  IconFlexiblePayments,
  IconShariaCompliant,
  IconService247,
  IconOffers,
  IconAbout,
  IconNews,
  AjilIcons,
} from './AjilIcons'

// Animated Icons
export {
  AnimatedAjilSymbol,
  AnimatedCarFinancing,
  AnimatedPersonalFinancing,
  AnimatedBusinessFinancing,
  AnimatedLoanCalculator,
  AnimatedSecurity,
  AnimatedQuickApproval,
  AnimatedFlexiblePayments,
  AnimatedShariaCompliant,
  AnimatedService247,
  AnimatedCustomerSupport,
  AnimatedOffers,
  AnimatedAbout,
  AnimatedNews,
  AnimatedLoadingSpinner,
  // New animated icons
  AnimatedRefresh,
  AnimatedTerms,
  AnimatedFaq,
  AnimatedBankTransfer,
  AnimatedCardPayment,
  AnimatedEditCoins,
  AnimatedAnalytics,
  AnimatedLogout,
  AnimatedDelete,
  AnimatedFolder,
  AnimatedInvoice,
  AnimatedEmailSupport,
  AnimatedPhoneSupport,
  AnimatedDarkMode,
  AnimatedLightMode,
  AnimatedIcons,
} from './AnimatedIcons'

// Logo Components
export {
  AjilLogo,
  AjilLogoMark,
  AjilLogoBackground,
  AjilWatermarkPattern,
} from './AjilLogo'
