export {
  AjilSymbol,
  IconLoanProducts,
  IconApplyFinancing,
  IconLoanCalculator,
  IconBusinessFinancing,
  IconPersonalFinancing,
  IconMurabaha,
  IconTrackApplication,
  IconCustomerSupport,
  IconHome,
  IconSettings,
  IconPayments,
  IconSecurity,
  IconCarFinancing,
  IconQuickApproval,
  IconFlexiblePayments,
  IconShariaCompliant,
  IconService247,
  IconOffers,
  IconNews,
  AjilIcons,
} from './AjilIcons'
